POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "Matthew",
    "password": "123456"
}

###
POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "mbriffett",
    "password": "123456",
    "emailAddres": "matthewbriffett@gmail.com",
    "displayName": "Matthew Briffett"
}

###
GET http://localhost:3000/api/auth/logout HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/movies/list HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNTMzMDhkOTUwOWUyMDFmOWJkM2FiNCIsImRpc3BsYXlOYW1lIjoiRGF2aWQgQ3VsdGFyZCIsInVzZXJuYW1lIjoiZGN1bHRhcmQiLCJpYXQiOjE2NjYzOTg5MjUsImV4cCI6MTY2NzAwMzcyNX0.cKUi_RvdeCLDmblXF7ND_lyQ7BhRVogXgqqzi1-R3lw
###
GET http://localhost:3000/api/movies/635338e3b855f51cfa4a32fd HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNTMzMDhkOTUwOWUyMDFmOWJkM2FiNCIsImRpc3BsYXlOYW1lIjoiRGF2aWQgQ3VsdGFyZCIsInVzZXJuYW1lIjoiZGN1bHRhcmQiLCJpYXQiOjE2NjYzOTg5MjUsImV4cCI6MTY2NzAwMzcyNX0.cKUi_RvdeCLDmblXF7ND_lyQ7BhRVogXgqqzi1-R3lw
###
POST http://localhost:3000/api/movies/add HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNTMzMDhkOTUwOWUyMDFmOWJkM2FiNCIsImRpc3BsYXlOYW1lIjoiRGF2aWQgQ3VsdGFyZCIsInVzZXJuYW1lIjoiZGN1bHRhcmQiLCJpYXQiOjE2NjYzOTg5MjUsImV4cCI6MTY2NzAwMzcyNX0.cKUi_RvdeCLDmblXF7ND_lyQ7BhRVogXgqqzi1-R3lw

{
    "name": "Reza Dibaj", 
    "phone":14163022619, 
    "email": "rdibaj@my.centennialcollege.ca",
}

###
PUT http://localhost:3000/api/movies/edit/63533b3b6ec77d14ea33eb95 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNTMzMDhkOTUwOWUyMDFmOWJkM2FiNCIsImRpc3BsYXlOYW1lIjoiRGF2aWQgQ3VsdGFyZCIsInVzZXJuYW1lIjoiZGN1bHRhcmQiLCJpYXQiOjE2NjYzOTg5MjUsImV4cCI6MTY2NzAwMzcyNX0.cKUi_RvdeCLDmblXF7ND_lyQ7BhRVogXgqqzi1-R3lw

{
    "name": "Courtney Stone", 
    "phone":17097254143, 
    "email": "courtneystone98@gmail.com",
}

###
DELETE http://localhost:3000/api/movies/delete/635338e3b855f51cfa4a32fd HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNTMzMDhkOTUwOWUyMDFmOWJkM2FiNCIsImRpc3BsYXlOYW1lIjoiRGF2aWQgQ3VsdGFyZCIsInVzZXJuYW1lIjoiZGN1bHRhcmQiLCJpYXQiOjE2NjYzOTg5MjUsImV4cCI6MTY2NzAwMzcyNX0.cKUi_RvdeCLDmblXF7ND_lyQ7BhRVogXgqqzi1-R3lw